name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if you're using that

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # change this if your HTML files are in a subfolder like ./docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
